:doctype: book
= Diploma Thesis : ScanBuyGo
Alexander Wiener; Dennis Sima; Lucas Walter; Florian Freimüller; Paul Maurovich
v1.0, 2018-06-18

:toc:
:toc-title: Inhaltsverzeichnis
:toclevels: 3

:blankline: pass:[ +]

[colophon, right]
== Colophon

{blankline}

*Spengergasse Press, Vienna*

(C) 2021 by Florian FREIMÜLLER, Paul MAUROVICH, Dennis SIMA, Lucas WALTER, Alexander WIENER

{blankline}

*Schuljahr 2020/21*

.Abgabevermerk
[cols="50,50", options="header"]
|===
|Datum:
|übernommen von:

|{blankline}
 {blankline}
|{blankline}
 {blankline}
|===

[eidesstattliche-erklaerung]
== Eidesstattliche Erklärung

Ich erkläre an Eides statt, dass ich die vorliegende Diplomarbeit selbständig
und ohne fremde Hilfe verfasst, andere als die angegebenen Quellen und
Hilfsmittel nicht benutzt und die den benutzten Quellen wörtlich und
inhaltlich entnommenen Stellen als solche erkenntlich gemacht habe.

[cols="30,70", options="header"]
|===
|Wien, am 07.04.2021
|VerfasserInnen

|{blankline}
|{blankline}
 {blankline}
 {blankline}
 Florian FREIMÜLLER

|{blankline}
|{blankline}
{blankline}
{blankline}
Paul MAUROVICH

|{blankline}
|{blankline}
{blankline}
{blankline}
Dennis SIMA

|{blankline}
|{blankline}
{blankline}
{blankline}
Lucas WALTER

|{blankline}
|{blankline}
{blankline}
{blankline}
Alexander WIENER
|===

[abstract]
== Abstract

//TODO

== Kurzfassung

//TODO

<<<

include::chapters/01-personal-topic-freimüller.adoc[]
include::chapters/02-personal-topic-maurovich.adoc[]
include::chapters/03-personal-topic-sima.adoc[]
include::chapters/04-personal-topic-walter.adoc[]
include::chapters/05-personal-topic-wiener.adoc[]

<<<


[appendix]
= Anhänge

image::../images/pdf/Kooperationsvertrag unterfertigt_2020-06-10_150551.pdf[pages=1..2]
image::../images/pdf/ScanBuyGo_User_Stories_final.pdf[pages=1..38]
image::../images/pdf/ScanBuyGo TOMs v2.pdf[pages=1..8]
image::../images/pdf/ScanBuyGo Procedural Directory (1).pdf[pages=1..9]
image::../images/pdf/Privacy Policy ScanBuyGo (1).pdf[pages=1..4]
image::../images/pdf/Project Health Monitor.pdf[pages=1..1]
image::../images/pdf/NoQuePOS_Vorstudien_v4.pdf[pages=1..33]
image::../images/pdf/ScanBuyGo_Statusbericht_1.pdf[pages=1..8]
image::../images/pdf/Besprechungsprotokoll 2020-06-18.pdf[pages=1..3]
image::../images/pdf/Besprechungsprotokoll 2020-06-23.pdf[pages=1..3]
image::../images/pdf/Besprechungsprotokoll 2020-06-25.pdf[pages=1..2]
image::../images/pdf/Besprechungsprotokoll 2020-07-02.pdf[pages=1..1]
image::../images/pdf/Besprechungsprotokoll 2020-07-03.pdf[pages=1..3]
image::../images/pdf/Besprechungsprotokoll 2020-07-19.pdf[pages=1..1]
image::../images/pdf/Besprechungsprotokoll 2020-07-23.pdf[pages=1..1]
image::../images/pdf/Besprechungsprotokoll 2020-07-25.pdf[pages=1..2]
image::../images/pdf/Besprechungsprotokoll 2020-07-30.pdf[pages=1..1]
image::../images/pdf/Besprechungsprotokoll 2020-08-26.pdf[pages=1..1]
image::../images/pdf/ChangeRequest_ScanBuyGo.pdf[pages=1..3]
image::../images/pdf/5BHIF NoQuePOS Stellungnahme Trennung Projektpartner.pdf[pages=1..6]
